# =============================================================================
# PKI Resources for cert-manager OCI DNS Webhook
# Uses cert-manager to generate TLS certificates for the webhook
# =============================================================================
# Note: Certificate and issuer name locals are defined in locals.tf

# -----------------------------------------------------------------------------
# Self-signed Issuer (bootstrap)
# Creates a self-signed issuer to bootstrap the CA certificate
# -----------------------------------------------------------------------------
resource "kubernetes_manifest" "self_signed_issuer" {
  count = var.enabled ? 1 : 0

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Issuer"
    metadata = {
      name      = local.self_signed_issuer_name
      namespace = var.namespace
      labels    = local.common_labels
    }
    spec = {
      selfSigned = {}
    }
  }

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }
}

# -----------------------------------------------------------------------------
# Root CA Certificate
# Generated by the self-signed issuer, used to sign webhook certificates
# -----------------------------------------------------------------------------
resource "kubernetes_manifest" "root_ca_certificate" {
  count = var.enabled ? 1 : 0

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Certificate"
    metadata = {
      name      = local.root_ca_certificate_name
      namespace = var.namespace
      labels    = local.common_labels
    }
    spec = {
      secretName = local.root_ca_certificate_name
      duration   = var.root_ca_duration
      issuerRef = {
        name = local.self_signed_issuer_name
      }
      commonName = "ca.${var.release_name}.cert-manager"
      isCA       = true
    }
  }

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }

  depends_on = [kubernetes_manifest.self_signed_issuer]
}

# -----------------------------------------------------------------------------
# CA Issuer
# Uses the root CA certificate to sign serving certificates
# -----------------------------------------------------------------------------
resource "kubernetes_manifest" "ca_issuer" {
  count = var.enabled ? 1 : 0

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Issuer"
    metadata = {
      name      = local.ca_issuer_name
      namespace = var.namespace
      labels    = local.common_labels
    }
    spec = {
      ca = {
        secretName = local.root_ca_certificate_name
      }
    }
  }

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }

  depends_on = [kubernetes_manifest.root_ca_certificate]
}

# -----------------------------------------------------------------------------
# Serving Certificate
# TLS certificate for the webhook's HTTPS endpoint
# -----------------------------------------------------------------------------
resource "kubernetes_manifest" "serving_certificate" {
  count = var.enabled ? 1 : 0

  manifest = {
    apiVersion = "cert-manager.io/v1"
    kind       = "Certificate"
    metadata = {
      name      = local.serving_certificate_name
      namespace = var.namespace
      labels    = local.common_labels
    }
    spec = {
      secretName = local.serving_certificate_name
      duration   = var.serving_cert_duration
      issuerRef = {
        name = local.ca_issuer_name
      }
      dnsNames = [
        var.release_name,
        "${var.release_name}.${var.namespace}",
        "${var.release_name}.${var.namespace}.svc"
      ]
    }
  }

  timeouts {
    create = "5m"
    update = "5m"
    delete = "5m"
  }

  depends_on = [kubernetes_manifest.ca_issuer]
}

# -----------------------------------------------------------------------------
# Wait for Root CA Certificate Secret
# The root CA secret contains the CA certificate (tls.crt) needed for the
# APIService's ca_bundle. This data source blocks until cert-manager has
# created the secret.
# -----------------------------------------------------------------------------
data "kubernetes_secret" "root_ca_certificate_secret" {
  count = var.enabled ? 1 : 0

  metadata {
    name      = local.root_ca_certificate_name
    namespace = var.namespace
  }

  depends_on = [kubernetes_manifest.root_ca_certificate]
}

# -----------------------------------------------------------------------------
# Wait for Serving Certificate Secret
# The kubernetes_manifest resource returns when the Certificate CR is created,
# but cert-manager processes it asynchronously. This data source blocks until
# cert-manager has actually created the Secret containing the TLS certificate.
# This prevents race conditions where the webhook Deployment tries to mount
# the secret before it exists.
# -----------------------------------------------------------------------------
data "kubernetes_secret" "serving_certificate_secret" {
  count = var.enabled ? 1 : 0

  metadata {
    name      = local.serving_certificate_name
    namespace = var.namespace
  }

  depends_on = [kubernetes_manifest.serving_certificate]
}
