output "cluster_id" {
  description = "The OCID of the OKE cluster"
  value       = oci_containerengine_cluster.logscale_cluster.id
}

output "vcn_id" {
  description = "The OCID of the VCN"
  value       = var.vcn_id
}

output "worker_nsg_id" {
  description = "The OCID of the worker NSG"
  value       = var.worker_nsg_id
}

# Note: Route table IDs are now exposed by the core module directly

output "node_pool_subnets" {
  description = "Map of node pool subnets"
  value       = var.node_pool_subnets
}

output "node_pools" {
  description = "Information about created node pools"
  value = {
    for k, v in oci_containerengine_node_pool.node_pools : k => {
      id   = v.id
      name = v.name
      size = v.node_config_details[0].size
    }
  }
}

output "worker_nodes_for_bastion" {
  description = "Worker node information formatted for bastion sessions"
  value       = local.worker_nodes_for_bastion
}

# Public route table ID is now exposed by the core module directly

# Keep CLI-friendly outputs
output "kubeconfig_command" {
  description = "Command to update kubeconfig"
  value       = "oci ce cluster create-kubeconfig --cluster-id ${oci_containerengine_cluster.logscale_cluster.id} --file $HOME/.kube/config --region ${var.region} --token-version 2.0.0 --profile ${var.oci_profile}"
}

output "kubeconfig_path" {
  description = "Path to the kubeconfig file"
  value       = "${path.root}/kubeconfig-${var.cluster_name}.yaml"
}

# Deterministic context name used by generated kubeconfig
# Provider-focused outputs: pull kubeconfig generated by OCI into Terraform
# Use the official data source to obtain a token-exec kubeconfig YAML for this cluster, and expose the exact context name returned.
data "oci_containerengine_cluster_kube_config" "this" {
  cluster_id    = oci_containerengine_cluster.logscale_cluster.id
  token_version = "2.0.0"
  # expiration  = 60
  # Note: Profile is handled by the OCI provider configuration, not as a parameter here
}

# Full kubeconfig YAML content for use by upstream modules/providers
# Modified to include the correct OCI profile in the exec command and tunnel configuration
output "kubeconfig_yaml" {
  description = "Parsed kubeconfig YAML content as a Terraform object for programmatic access"
  value = merge(
    yamldecode(data.oci_containerengine_cluster_kube_config.this.content),
    {
      users = [
        merge(
          yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0],
          {
            user = merge(
              yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"],
              {
                exec = merge(
                  yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"]["exec"],
                  {
                    args = concat(
                      yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"]["exec"]["args"],
                      ["--profile", var.oci_profile]
                    )
                  }
                )
              }
            )
          }
        )
      ]
    }
  )
}

# Tunnel-compatible kubeconfig for SSH tunnel access
output "kubeconfig_yaml_tunnel" {
  description = "Tunnel-compatible kubeconfig YAML for SSH tunnel access (localhost:6443 with insecure-skip-tls-verify)"
  value = merge(
    yamldecode(data.oci_containerengine_cluster_kube_config.this.content),
    {
      clusters = [
        merge(
          yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["clusters"][0],
          {
            cluster = {
              server                   = "https://localhost:6443"
              insecure-skip-tls-verify = true
            }
          }
        )
      ]
      users = [
        merge(
          yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0],
          {
            user = merge(
              yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"],
              {
                exec = merge(
                  yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"]["exec"],
                  {
                    args = concat(
                      yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["users"][0]["user"]["exec"]["args"],
                      ["--profile", var.oci_profile]
                    )
                  }
                )
              }
            )
          }
        )
      ]
    }
  )
}

# The OCI data source does not export the context name; build the expected value using the cluster OCID
# This matches the value used by oci ce cluster create-kubeconfig
output "kubeconfig_context" {
  description = "Kubeconfig context name for the cluster"
  value       = "context-${oci_containerengine_cluster.logscale_cluster.id}"
}

# Locals for kubeconfig transformation
locals {
  # Parse the raw kubeconfig from OCI
  raw_kubeconfig = yamldecode(data.oci_containerengine_cluster_kube_config.this.content)

  # Determine if we should use public endpoint directly (no bastion tunnel needed)
  use_public_endpoint = var.endpoint_public_access && !var.provision_bastion && var.kubernetes_api_host == ""

  # Kubernetes host: use override if provided, otherwise use kubeconfig value
  kubernetes_host = var.kubernetes_api_host != "" ? var.kubernetes_api_host : local.raw_kubeconfig.clusters[0].cluster.server

  # Build kubeconfig with:
  # 1. cluster_name as context/cluster/user names (instead of OCI-generated context-<ocid>)
  # 2. OCI profile and auth args for authentication
  # This ensures consistent naming across workspaces and proper kubectl authentication
  kubeconfig_with_cluster_name = {
    apiVersion = local.raw_kubeconfig.apiVersion
    kind       = local.raw_kubeconfig.kind
    clusters = [
      {
        name    = var.cluster_name
        cluster = local.raw_kubeconfig.clusters[0].cluster
      }
    ]
    contexts = [
      {
        name = var.cluster_name
        context = {
          cluster = var.cluster_name
          user    = "${var.cluster_name}-user"
        }
      }
    ]
    "current-context" = var.cluster_name
    users = [
      {
        name = "${var.cluster_name}-user"
        user = {
          exec = merge(
            local.raw_kubeconfig.users[0].user.exec,
            {
              args = concat(
                local.raw_kubeconfig.users[0].user.exec.args,
                ["--profile", var.oci_profile, "--auth", "api_key"]
              )
            }
          )
        }
      }
    ]
  }
}

# Output the transformed kubeconfig with cluster_name as context
output "kubeconfig_with_cluster_name" {
  description = "Kubeconfig YAML with cluster_name as context name (instead of OCI-generated context-<ocid>)"
  value       = local.kubeconfig_with_cluster_name
}

# Output the Kubernetes host (for provider configuration)
output "kubernetes_host" {
  description = "Kubernetes API host URL"
  value       = local.kubernetes_host
}

# Output raw kubeconfig content for provider configuration
output "raw_kubeconfig" {
  description = "Raw kubeconfig parsed from OCI data source"
  value       = local.raw_kubeconfig
}

# Output the kubeconfig as YAML string (ready to write to file)
output "kubeconfig_yaml_string" {
  description = "Kubeconfig as YAML string, ready to write to a file"
  value       = yamlencode(local.kubeconfig_with_cluster_name)
}

output "worker_image_info" {
  description = "Information about the worker image being used"
  value = {
    # Image ID used by worker nodes (extracted from actual node pools)
    image_id = length(oci_containerengine_node_pool.node_pools) > 0 ? values(oci_containerengine_node_pool.node_pools)[0].node_source_details[0].image_id : var.worker_image_id

    # Original variable value for comparison
    provided_image_id = var.worker_image_id

    # Per-node-pool image information
    node_pool_images = {
      for k, v in oci_containerengine_node_pool.node_pools : k => {
        image_id         = v.node_source_details[0].image_id
        boot_volume_size = v.node_source_details[0].boot_volume_size_in_gbs
        source_type      = v.node_source_details[0].source_type
      }
    }

    # Summary information
    total_node_pools = length(oci_containerengine_node_pool.node_pools)
    unique_images    = length(distinct([for v in oci_containerengine_node_pool.node_pools : v.node_source_details[0].image_id]))
  }
}

# Output the policy OCIDs for reference
# output "iam_policy_ocids" {
#   description = "OCIDs of the created IAM policies"
#   value = var.create_iam_resources ? {
#     compute_policy       = oci_identity_policy.logscale_compute_policy[0].id
#     network_policy       = oci_identity_policy.logscale_network_policy[0].id
#     oke_policy          = oci_identity_policy.logscale_oke_policy[0].id
#     storage_policy      = oci_identity_policy.logscale_storage_policy[0].id
#     iam_policy          = oci_identity_policy.logscale_iam_policy[0].id
#     dynamic_group_policy = oci_identity_policy.logscale_dynamic_group_policy[0].id
#   } : {}
# }

# output "dynamic_group_ocid" {
#   description = "OCID of the created dynamic group"
#   value       = var.create_iam_resources ? oci_identity_dynamic_group.logscale_oke_dynamic_group[0].id : null
# }

# output "logscale_group_ocid" {
#   description = "OCID of the created LogScale user group"
#   value       = var.create_iam_resources ? oci_identity_group.logscale_group[0].id : null
# }

# Kubernetes cluster connection informatio

# Additional endpoint information for debugging and monitoring
output "cluster_endpoint_details" {
  description = "Detailed cluster endpoint information including public and private endpoints"
  value = length(oci_containerengine_cluster.logscale_cluster.endpoints) > 0 ? {
    kubernetes_endpoint = oci_containerengine_cluster.logscale_cluster.endpoints[0].kubernetes
    public_endpoint     = try(oci_containerengine_cluster.logscale_cluster.endpoints[0].public_endpoint, null)
    private_endpoint    = try(oci_containerengine_cluster.logscale_cluster.endpoints[0].private_endpoint, null)
    is_public_enabled   = oci_containerengine_cluster.logscale_cluster.endpoint_config[0].is_public_ip_enabled
  } : null
  sensitive = false
}

# Note: CA certificate is extracted from the kubeconfig data source
# The kubeconfig contains the cluster CA certificate in base64 encoded format
output "cluster_ca_certificate" {
  description = "Kubernetes cluster CA certificate"
  value       = yamldecode(data.oci_containerengine_cluster_kube_config.this.content)["clusters"][0]["cluster"]["certificate-authority-data"]
  sensitive   = true
}

output "cluster_name" {
  description = "Name of the Kubernetes cluster"
  value       = oci_containerengine_cluster.logscale_cluster.name
}

output "region" {
  description = "OCI region where the cluster is deployed"
  value       = var.region
}

# Enhanced monitoring and health check outputs
output "cluster_health_status" {
  description = "Comprehensive cluster health and status information"
  value = {
    cluster_id         = oci_containerengine_cluster.logscale_cluster.id
    cluster_state      = oci_containerengine_cluster.logscale_cluster.state
    lifecycle_details  = try(oci_containerengine_cluster.logscale_cluster.lifecycle_details, "N/A")
    kubernetes_version = oci_containerengine_cluster.logscale_cluster.kubernetes_version
    cluster_type       = oci_containerengine_cluster.logscale_cluster.type
    compartment_id     = oci_containerengine_cluster.logscale_cluster.compartment_id
  }
}

output "network_configuration" {
  description = "Network configuration details"
  value = {
    vcn_id        = var.vcn_id
    vcn_cidr      = var.vcn_cidr
    pods_cidr     = var.pods_cidr
    services_cidr = var.services_cidr
    cni_type      = var.cni_type

    subnets = {
      cluster_endpoint = {
        id   = var.cluster_endpoint_subnet_id
        cidr = var.cluster_endpoint_subnet_cidr
      }
      load_balancer = {
        id   = var.lb_subnet_id
        cidr = var.lb_subnet_cidr
      }
      pods = {
        id   = var.pod_subnet_id
        cidr = var.pods_cidr
      }
      node_pools = var.node_pool_subnets
    }

    security_groups = {
      worker_nsg_id       = var.worker_nsg_id
      api_endpoint_nsg_id = var.api_endpoint_nsg_id
    }
  }
}

output "resource_tags" {
  description = "Tags applied to cluster resources"
  value = merge(var.common_tags, var.mandatory_tags, {
    "ClusterName" = var.cluster_name
    "Module"      = "oci-oke"
  })
}

output "cluster_features" {
  description = "Enabled cluster features and add-ons"
  value = {
    cluster_type        = var.cluster_type
    dashboard_enabled   = var.is_kubernetes_dashboard_enabled
    tiller_enabled      = var.is_tiller_enabled
    pod_security_policy = var.enable_pod_security_policy
    public_endpoint     = var.endpoint_public_access
    cluster_autoscaler  = var.enable_cluster_autoscaler
  }
}


output "troubleshooting_info" {
  description = "Information useful for troubleshooting"
  value = {
    cluster_id     = oci_containerengine_cluster.logscale_cluster.id
    compartment_id = var.compartment_ocid
    region         = var.region

    kubectl_context = "context-${oci_containerengine_cluster.logscale_cluster.id}"

    get_kubeconfig_cmd = "oci ce cluster create-kubeconfig --cluster-id ${oci_containerengine_cluster.logscale_cluster.id} --file $HOME/.kube/config --region ${var.region} --token-version 2.0.0 --profile ${var.oci_profile}"

    list_nodes_cmd = "kubectl get nodes -o wide"

    check_pods_cmd = "kubectl get pods --all-namespaces"

    bastion_plugin_enabled = var.enable_bastion_plugin
  }
}

# DNS failover outputs moved to root level outputs since DNS resources are managed there
